
-- 1. Справочник рейтингов MPA
CREATE TABLE IF NOT EXISTS mpa (
    id INTEGER PRIMARY KEY,
    name VARCHAR(50) NOT NULL
    );

-- 2. Справочник жанров
CREATE TABLE IF NOT EXISTS genre (
    genre_id INTEGER PRIMARY KEY,
    genre_name VARCHAR(50) NOT NULL
    );

-- 3. Статусы дружбы
CREATE TABLE IF NOT EXISTS friendship_status (
    status_id INTEGER PRIMARY KEY,
    status_name VARCHAR(50) NOT NULL
    );

-- 4. Пользователи
CREATE TABLE IF NOT EXISTS users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    login VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    birthday DATE
    );

-- 5. Фильмы
CREATE TABLE IF NOT EXISTS films (
    film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    mpa_id INTEGER REFERENCES mpa (id),
    description VARCHAR(200),
    release_date DATE,
    duration INTEGER
    );

-- 6. Таблица связей Фильм-Жанр (многие ко многим)
CREATE TABLE IF NOT EXISTS film_genre (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id INTEGER REFERENCES films (film_id) ON DELETE CASCADE,
    genre_id INTEGER REFERENCES genre (genre_id) ON DELETE CASCADE
    );

-- 7. Лайки фильмов
CREATE TABLE IF NOT EXISTS film_likes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id INTEGER REFERENCES films (film_id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users (user_id) ON DELETE CASCADE
    );

-- 8. Дружба между пользователями
CREATE TABLE IF NOT EXISTS friends (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users (user_id) ON DELETE CASCADE,
    friend_id INTEGER REFERENCES users (user_id) ON DELETE CASCADE,
    status_id INTEGER REFERENCES friendship_status (status_id) ON DELETE CASCADE
    );